architect:
    - Slach
# /** @todo #1:15m/QA check 0pdd.com for parse short variant of puzzles? */
# docker:
#    image: bloodjazman/juno_kv_server
#    directory: repo/Dockerfile
install: |
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 136221EE520DDFAF0A905689B9316A7BC7917B12
    add-apt-repository ppa:gophers/archive
    apt-get update
    apt-get install -y golang-1.8
    ln -nvsf /usr/lib/go-1.8/bin/go /bin/go
    ln -nvsf /usr/lib/go-1.8/bin/gofmt /bin/gofmt
    bash -c "cd /home/r/src && GOPATH=/home/r go get -v ./..."

merge:
    script: |
        GOPATH=/home/r go test junoKvClient -test.v -test.bench . -test.run . -test.benchtime 10s
        GOPATH=/home/r go test junoKvServer -test.v -test.bench . -test.run . -test.benchtime 10s

# /** @todo #1:15m/QA uncomment this after resolve https://github.com/golang/go/issues/14481 */
#        /juno-test/bin/kv_server_bench_race -test.v -test.bench . -test.run ^$ -test.benchtime 10s
#        /juno-test/bin/kv_client_bench_race -test.v -test.bench . -test.run ^$ -test.benchtime 10s
    squash: true
    rebase: true
    fast-forward: default
